// GENERATED by tools/gen-db-names.mjs — do not hand-edit.
//
// Regenerate after adding a column or a new "AS alias" to a query:
//   node tools/gen-db-names.mjs

// Lower case -> the camelCase key storage.js actually reads. PostgreSQL folds
// unquoted identifiers to lower case, so every row it returns is keyed in lower
// case; db/postgres.js renames them through this map before storage.js sees
// them. Names that are already lower case are absent on purpose — they need no
// mapping, and listing them would only invite drift.
export const CANONICAL_KEYS = Object.freeze({
  "addedat": "addedAt",
  "assetcreationdate": "assetCreationDate",
  "assetfilepath": "assetFilePath",
  "assetheight": "assetHeight",
  "assetid": "assetId",
  "assetmetadata": "assetMetadata",
  "assetname": "assetName",
  "assetparentid": "assetParentId",
  "assetposition": "assetPosition",
  "assetthumbnail": "assetThumbnail",
  "assettypeid": "assetTypeId",
  "assettypename": "assetTypeName",
  "assetwidth": "assetWidth",
  "attributetypeid": "attributeTypeId",
  "attributetypename": "attributeTypeName",
  "attributevalue": "attributeValue",
  "basefilepath": "baseFilePath",
  "bonecount": "boneCount",
  "cardid": "cardId",
  "cardmetadata": "cardMetadata",
  "cardname": "cardName",
  "cardposition": "cardPosition",
  "cardprogress": "cardProgress",
  "cardstatus": "cardStatus",
  "childid": "childId",
  "clientkey": "clientKey",
  "columnname": "columnName",
  "createdat": "createdAt",
  "creationdate": "creationDate",
  "displayname": "displayName",
  "editfilepath": "editFilePath",
  "editheight": "editHeight",
  "editmetadata": "editMetadata",
  "editname": "editName",
  "editwidth": "editWidth",
  "filepath": "filePath",
  "framecount": "frameCount",
  "graphviewport": "graphViewport",
  "inplace": "inPlace",
  "inputid": "inputId",
  "islinked": "isLinked",
  "kanbancolumnid": "kanbanColumnId",
  "kanbancolumnname": "kanbanColumnName",
  "lastloginat": "lastLoginAt",
  "layersjson": "layersJson",
  "nextposition": "nextPosition",
  "nodetypeid": "nodeTypeId",
  "nodetypename": "nodeTypeName",
  "outputid": "outputId",
  "outputsjson": "outputsJson",
  "ownerid": "ownerId",
  "ownername": "ownerName",
  "parametersjson": "parametersJson",
  "parentfilepath": "parentFilePath",
  "parentid": "parentId",
  "parentprojectid": "parentProjectId",
  "passwordhash": "passwordHash",
  "projectid": "projectId",
  "projectname": "projectName",
  "rigkey": "rigKey",
  "sourceassetid": "sourceAssetId",
  "sourcecardid": "sourceCardId",
  "sourceclip": "sourceClip",
  "sourcemesh": "sourceMesh",
  "sourcenodeid": "sourceNodeId",
  "statejson": "stateJson",
  "targetcardid": "targetCardId",
  "targetnodeid": "targetNodeId",
  "textureheight": "textureHeight",
  "texturewidth": "textureWidth",
  "thumbnailpath": "thumbnailPath",
  "typename": "typeName",
  "updatedat": "updatedAt",
  "xpos": "xPos",
  "ypos": "yPos"
});

// Tables whose primary key is a single `id` column, lower-cased because that is
// how PostgreSQL stores the table name and how the driver looks it up. Anything
// absent here is keyed by a composite or a foreign id, and must never have
// RETURNING id appended to its inserts.
export const TABLES_WITH_ID = Object.freeze(new Set([
  "assets",
  "assettypes",
  "attributes",
  "boards",
  "cards",
  "columns",
  "customanimations",
  "motions",
  "nodetypes",
  "projects",
  "settings",
  "users",
  "wikipages"
]));
