-- GENERATED by tools/gen-pg-schema.mjs from the schema in storage.js.
-- Do not hand-edit: change storage.js and regenerate, or the two engines drift.
--
-- Identifiers are deliberately UNQUOTED. PostgreSQL folds them to lower case,
-- which is exactly what lets storage.js keep its camelCase queries unchanged --
-- `SELECT filePath FROM Assets` lower-cases on both sides and matches. Rows come
-- back lower-cased and db/postgres.js maps the keys back via db/names.js.
--
-- The one-time legacy migrations in storage.js (Nodes->Cards, Assets_Edits) are
-- NOT represented here and never run against PostgreSQL: a Postgres database is
-- either created fresh from this file or populated by
-- tools/migrate-sqlite-to-postgres.mjs, so it cannot be in a pre-migration state.

CREATE TABLE IF NOT EXISTS Projects (
      id BIGINT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      preset TEXT,
      creationDate BIGINT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      ownerId BIGINT
);

CREATE TABLE IF NOT EXISTS Columns (
      id BIGINT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      position BIGINT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS NodeTypes (
      id BIGINT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Cards (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      projectId BIGINT NOT NULL,
      kanbanColumnId BIGINT,
      nodeTypeId BIGINT,
      clientKey TEXT,
      name TEXT,
      position BIGINT,
      xPos DOUBLE PRECISION NOT NULL DEFAULT 0,
      yPos DOUBLE PRECISION NOT NULL DEFAULT 0,
      creationDate BIGINT NOT NULL,
      status TEXT,
      progress BIGINT,
      metadata TEXT,
      FOREIGN KEY(projectId) REFERENCES Projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(kanbanColumnId) REFERENCES Columns(id) DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(nodeTypeId) REFERENCES NodeTypes(id) DEFERRABLE INITIALLY IMMEDIATE,
      UNIQUE(projectId, kanbanColumnId, position),
      UNIQUE(projectId, clientKey)
);

CREATE TABLE IF NOT EXISTS AssetTypes (
      id BIGINT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Attributes (
      id BIGINT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Assets (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      filePath TEXT NOT NULL,
      assetTypeId BIGINT NOT NULL,
      creationDate BIGINT NOT NULL,
      metadata TEXT,
      thumbnail TEXT,
      width BIGINT NOT NULL DEFAULT 0,
      height BIGINT NOT NULL DEFAULT 0,
      parentId BIGINT,
      -- Who created or imported this. See Projects.ownerId for the full rules;
      -- an edit or version inherits its parent's owner so a chain never splits
      -- between two libraries.
      ownerId BIGINT,
      FOREIGN KEY(parentId) REFERENCES Assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(assetTypeId) REFERENCES AssetTypes(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS Cards_Assets (
      cardId BIGINT NOT NULL,
      assetId BIGINT NOT NULL,
      position BIGINT NOT NULL,
      PRIMARY KEY(cardId, assetId),
      FOREIGN KEY(cardId) REFERENCES Cards(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(assetId) REFERENCES Assets(id) ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
      UNIQUE(cardId, position)
);

CREATE TABLE IF NOT EXISTS Cards_Attributes (
      cardId BIGINT NOT NULL,
      position BIGINT NOT NULL,
      attributeTypeId BIGINT NOT NULL,
      attributeValue TEXT,
      PRIMARY KEY(cardId, position),
      FOREIGN KEY(cardId) REFERENCES Cards(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(attributeTypeId) REFERENCES Attributes(id) DEFERRABLE INITIALLY IMMEDIATE,
      UNIQUE(cardId, position)
);

CREATE TABLE IF NOT EXISTS WorkflowConfigs (
      assetId BIGINT PRIMARY KEY,
      parametersJson TEXT NOT NULL DEFAULT '[]',
      outputsJson TEXT NOT NULL DEFAULT '[]',
      -- Which user imported this workflow. A workflow is written against one
      -- person's ComfyUI -- their models, their node packs -- so on a shared
      -- server everyone gets their own library rather than one global set that
      -- the next import replaces.
      --
      -- NULL means unowned, and stays visible to everyone. That is every
      -- workflow on a single-user desktop install, where there are no accounts
      -- to own anything and the behaviour must be exactly as before.
      ownerId BIGINT,
      FOREIGN KEY(assetId) REFERENCES Assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS Settings (
      id BIGINT PRIMARY KEY CHECK (id = 1),
      json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      login TEXT NOT NULL UNIQUE,
      displayName TEXT,
      passwordHash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user',
      avatar TEXT,
      createdAt BIGINT NOT NULL,
      lastLoginAt BIGINT,
      disabled BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Connections (
      sourceCardId BIGINT NOT NULL,
      targetCardId BIGINT NOT NULL,
      inputId TEXT NOT NULL,
      outputId TEXT NOT NULL,
      PRIMARY KEY(sourceCardId, targetCardId, inputId, outputId),
      FOREIGN KEY(sourceCardId) REFERENCES Cards(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(targetCardId) REFERENCES Cards(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS PaintDocuments (
      assetId BIGINT PRIMARY KEY,
      baseFilePath TEXT,
      textureWidth BIGINT NOT NULL DEFAULT 0,
      textureHeight BIGINT NOT NULL DEFAULT 0,
      layersJson TEXT NOT NULL DEFAULT '[]',
      updatedAt BIGINT NOT NULL,
      FOREIGN KEY(assetId) REFERENCES Assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS WikiPages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      parentId BIGINT,
      title TEXT NOT NULL,
      icon TEXT,
      content TEXT NOT NULL DEFAULT '',
      position BIGINT NOT NULL DEFAULT 0,
      createdAt BIGINT NOT NULL,
      updatedAt BIGINT NOT NULL,
      FOREIGN KEY(parentId) REFERENCES WikiPages(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS Boards (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      projectId BIGINT NOT NULL,
      name TEXT NOT NULL,
      position BIGINT NOT NULL DEFAULT 0,
      stateJson TEXT,
      thumbnailPath TEXT,
      createdAt BIGINT NOT NULL,
      updatedAt BIGINT NOT NULL,
      FOREIGN KEY(projectId) REFERENCES Projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS BatchConfigs (
      projectId BIGINT PRIMARY KEY,
      stateJson TEXT NOT NULL DEFAULT '{}',
      updatedAt BIGINT NOT NULL,
      FOREIGN KEY(projectId) REFERENCES Projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS Assets_Projects (
      assetId BIGINT NOT NULL,
      projectId BIGINT NOT NULL,
      addedAt BIGINT NOT NULL,
      PRIMARY KEY(assetId, projectId),
      FOREIGN KEY(assetId) REFERENCES Assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
      FOREIGN KEY(projectId) REFERENCES Projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS Motions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      prompt TEXT NOT NULL,
      -- Seconds of motion, read back out of the BVH rather than taken from the
      -- request: a multi-sentence prompt generates one segment per sentence, so
      -- what was asked for and what came back routinely differ.
      duration DOUBLE PRECISION NOT NULL DEFAULT 0,
      frameCount BIGINT NOT NULL DEFAULT 0,
      fps DOUBLE PRECISION NOT NULL DEFAULT 0,
      inPlace BIGINT NOT NULL DEFAULT 0,
      seed BIGINT,
      filePath TEXT NOT NULL,
      -- Which generator produced it: 'kimodo' (text to motion) or 'mocap' (video
      -- to motion). Not bookkeeping — it decides how the stored BVH is treated on
      -- the way back out. What is saved is the RAW generator output, and a MoCap
      -- root carries a bogus body tilt that has to be straightened on apply,
      -- whereas a Kimodo root tilt is real motion ("lie down"). Without this
      -- column a re-applied capture comes back tipped over.
      source TEXT NOT NULL DEFAULT 'kimodo',
      createdAt BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS CustomAnimations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      -- Where the clip came from, for the library row: the mesh it was edited on
      -- and the clip name it started life as.
      sourceMesh TEXT NOT NULL DEFAULT '',
      sourceClip TEXT NOT NULL DEFAULT '',
      duration DOUBLE PRECISION NOT NULL DEFAULT 0,
      frameCount BIGINT NOT NULL DEFAULT 0,
      fps DOUBLE PRECISION NOT NULL DEFAULT 0,
      boneCount BIGINT NOT NULL DEFAULT 0,
      -- Identifies the SKELETON the clip was authored on (a hash of its bone
      -- names). Two animations saved off the same rig share it, which is what
      -- lets a bone mapping made for one be reused for the others.
      rigKey TEXT NOT NULL DEFAULT '',
      filePath TEXT NOT NULL,
      createdAt BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS MeshAssemblies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      stateJson TEXT,
      thumbnailPath TEXT,
      createdAt BIGINT NOT NULL,
      updatedAt BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Assets_Tags (
      assetId BIGINT NOT NULL,
      tag TEXT NOT NULL,
      addedAt BIGINT NOT NULL,
      PRIMARY KEY(assetId, tag),
      FOREIGN KEY(assetId) REFERENCES Assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

ALTER TABLE Assets ADD COLUMN IF NOT EXISTS thumbnail TEXT;

ALTER TABLE Assets ADD COLUMN IF NOT EXISTS width BIGINT NOT NULL DEFAULT 0;

ALTER TABLE Assets ADD COLUMN IF NOT EXISTS height BIGINT NOT NULL DEFAULT 0;

ALTER TABLE Assets ADD COLUMN IF NOT EXISTS parentId BIGINT;

ALTER TABLE Assets ADD COLUMN IF NOT EXISTS ownerId BIGINT;

ALTER TABLE WorkflowConfigs ADD COLUMN IF NOT EXISTS ownerId BIGINT;

ALTER TABLE Projects ADD COLUMN IF NOT EXISTS graphViewport TEXT;

ALTER TABLE Projects ADD COLUMN IF NOT EXISTS ownerId BIGINT;

CREATE INDEX IF NOT EXISTS idx_wikipages_parentId ON WikiPages(parentId);

CREATE INDEX IF NOT EXISTS idx_boards_projectId ON Boards(projectId);

CREATE INDEX IF NOT EXISTS idx_assets_projects_projectId ON Assets_Projects(projectId);

CREATE INDEX IF NOT EXISTS idx_assets_tags_tag ON Assets_Tags(tag);

CREATE INDEX IF NOT EXISTS idx_motions_createdAt ON Motions(createdAt);

CREATE INDEX IF NOT EXISTS idx_customanimations_createdAt ON CustomAnimations(createdAt);

CREATE INDEX IF NOT EXISTS idx_assets_parentId ON Assets(parentId);

CREATE INDEX IF NOT EXISTS idx_assets_ownerId ON Assets(ownerId);

CREATE INDEX IF NOT EXISTS idx_projects_ownerId ON Projects(ownerId);

CREATE INDEX IF NOT EXISTS idx_cards_projectId ON Cards(projectId);

CREATE INDEX IF NOT EXISTS idx_connections_sourceCardId ON Connections(sourceCardId);

CREATE INDEX IF NOT EXISTS idx_connections_targetCardId ON Connections(targetCardId);

CREATE INDEX IF NOT EXISTS idx_assets_filePath ON Assets(filePath);

CREATE INDEX IF NOT EXISTS idx_assets_thumbnail ON Assets(thumbnail);

CREATE INDEX IF NOT EXISTS idx_cards_assets_assetId ON Cards_Assets(assetId);

CREATE UNIQUE INDEX IF NOT EXISTS users_login_lower_key ON Users (lower(login));
